### ISSUE TITLE
Not able to run codes in edaplayground.com, When clicking run page refreshes automatically

### ISSUE THREAD

**Issue by ojhatapaskumarr** [edaplayground/eda-playground#38]
Hi Team,
My edaplayground.com account is registered with my college mail-id **m160006ec@nitsikkim.ac.in**. 
I am not able to run any code. When I am trying to run a code, the page automatically refreshes instead of giving any result. Also, I am not able to run my previous codes from my playground. The same issue is happening with these codes also.
Please help.

Thanks and regards,
Tapas

**Comment by edaplayground** [comment]
Hi Tapas,

Please can you try logging in and out again; deleting all the cookies; a different browser - that sort of thing. Then let me know how you get on.

Matthew

**Comment by ojhatapaskumarr** [comment]
Thank you Matthew for your timely reply. It got resolved after logging out and logging in again.
