### ISSUE TITLE
Feature suggestion: create action in GitHub for CI/CD

### ISSUE THREAD

**Issue by smirnovich** [edaplayground/eda-playground#43]
Nowadays only VUnit is available for a regular HDL repository in GitHub. Since it needs modelling software and the resources of GitHub is limited, the only one they use is GHDL. But GHDL is very limited - i.e. it doesn't support SystemVerilog.

The idea is to use EDAPlayground as a part of CI/CD in GitHub

**Comment by edaplayground** [comment]
Thank you for your suggestion. Unfortunately, this will not be possible. I could create an API to allow people to run simulations on EDA Playground automatically, but not only would this result in us providing compute resource to the world free of charge, much more importantly it would deprive the EDA vendors of their well-deserved revenue.
