### ISSUE TITLE
Eda playground erroring out when tried to open "Your playgrounds" - please help

### ISSUE THREAD

**Issue by SomaSaiCharitha** [edaplayground/eda-playground#68]
<img width="435" alt="Screenshot 2022-08-02 181346" src="https://user-images.githubusercontent.com/30781720/182503035-0478e66c-68d1-40db-ab61-e65095ffdbfa.png">

**Comment by mpataylor** [comment]
I'm not sure what was going on. One of the servers was acting strangely. A reboot sorted it out. Sorry for the inconvenience.

**Comment by SomaSaiCharitha** [comment]
thanks , issue is resolved now!
